<?php

namespace S\VentasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonasRe
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonasRe extends EntityRepository
{
}
