<?php

namespace S\VentasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserEventoRe
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEventoRe extends EntityRepository
{
}
